site_name: Netbox Circuit Maintenance Plugin
site_url: https://jasonyates.github.io/netbox-circuitmaintenance
repo_url: https://github.com/jasonyates/netbox-circuitmaintenance
repo_name: jasonyates/netbox_circuitmaintenance
#strict: true
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - netbox_circuitmaintenance
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/netbox-community/cookiecutter-netbox-plugin
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/netbox-community/cookiecutter-netbox-plugin
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/jasonyates/netbox-circuitmaintenance
      name: Github
    - icon: material/email
      link: "mailto:me@jasonyates.co.uk"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
